[package]
name = "qubic-cli"
version = "0.0.1"
authors = ["kination <kination27@gmail.com>"]
edition = "2021"

[dependencies]
s2n-quic = { version = "1" }
tokio = { version = "1", features = ["full"] }

[[bin]]
name = "cli"
path = "src/main.rs"

