[package]
name = "qubic-server"
version = "0.0.1"
authors = ["kination <inylove82@gmail.com>"]
edition = "2021"
rust-version = "1.63"

[dependencies]
s2n-quic = { version = "1" }
tokio = { version = "1", features = ["full"] }

[[bin]]
name = "server"
path = "src/server.rs"
